FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN rm -r src/SentiCR
RUN rm src/analysis.py

CMD ["python", "calculate.py"]
