FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt \
	&& pip install --no-cache-dir --index-url https://download.pytorch.org/whl/cu121 torch

COPY . .

RUN rm src/calculate.py

CMD ["python", "src/analysis.py"]
